riverctl send-layout-cmd stacktile "primary_count 1"
riverctl send-layout-cmd stacktile "primary_ratio 0.55"
riverctl send-layout-cmd stacktile "primary_sublayout rows"
riverctl send-layout-cmd stacktile "primary_position left"
riverctl send-layout-cmd stacktile "secondary_count 0"
riverctl send-layout-cmd stacktile "secondary_ratio 0.45"
riverctl send-layout-cmd stacktile "secondary_sublayout rows"
riverctl send-layout-cmd stacktile "remainder_sublayout rows"
riverctl send-layout-cmd stacktile "all_padding 4"
riverctl send-layout-cmd stacktile "all_primary false"

dunstify -u low "RiverWM" "Switched to Default Layout"
