riverctl send-layout-cmd stacktile "primary_count 1"
riverctl send-layout-cmd stacktile "primary_ratio 1.0"
riverctl send-layout-cmd stacktile "primary_sublayout full"
riverctl send-layout-cmd stacktile "primary_position left"
riverctl send-layout-cmd stacktile "secondary_count 0"
riverctl send-layout-cmd stacktile "secondary_ratio 0"
riverctl send-layout-cmd stacktile "secondary_sublayout rows"
riverctl send-layout-cmd stacktile "remainder_sublayout rows"
riverctl send-layout-cmd stacktile "all_padding 0"
riverctl send-layout-cmd stacktile "all_primary true"

dunstify -u low "RiverWM" "Switched to Monocle Layout"
