# preload = /home/hamza/pix/walls/rockman.jpg
# preload = /home/hamza/pix/walls/fuji-san.jpg
# preload = /home/hamza/pix/walls/fuji-san-2.jpg 
# preload = /home/hamza/pix/walls/jp-subway-goldfish.jpg

wallpaper {
    monitor = # HDMI-A-2
    path = ~/pix/walls/fuji-san.jpg
    #fit_mode = cover
}