bar:
   font: mononoki:pixelsize=17:slant=normal
   location: top
   height: 26
   foreground: ebdbb2ff
   background: 282828ff
   margin: 5 

   border:
     color: 504945ff
     bottom-width: 2

   left:
     - river:
         title:
           map:
             conditions:
               mode == "normal":
                 - string:
                     text: "| {title}"
               mode == "passthrough":
                 - string:
                     text: "| [->] {title}"
         content:
           map:
             on-click:
               left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
               right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
               middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
             conditions:
               id == 1:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                                 right-margin: 5
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: ""
                                 right-margin: 5
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                                 right-margin: 5
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
                                 right-margin: 5
               id == 2:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: "󰈹"
                                 left-margin: 1
                                 right-margin: 5
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: "󰈹"
                                 right-margin: 5
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: "󰈹 "
                                 right-margin: 5
                           ~occupied:
                             - string:
                                 foreground: a89984ff
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: "󰈹 "
                                 right-margin: 5
               id == 3:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                                 right-margin: 8
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: ""
                                 right-margin: 8
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                                 right-margin: 8
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
                                 right-margin: 8
               id == 4:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                                 right-margin: 9
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: ""
                                 right-margin: 9
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                                 right-margin: 9
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
                                 right-margin: 9
               id == 5:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                                 right-margin: 3
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: ""
                                 right-margin: 3
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                                 right-margin: 3
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
                                 right-margin: 3
               id == 6:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: ""
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
               id == 7:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=20:regular"
                                 text: "󰕧"
                                 right-margin: 2
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: "󰕧"
                                 right-margin: 2
                                 font: "SauceCodePro Nerd Font:size=20:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=20:regular"
                                 text: "󰕧 "
                                 right-margin: 2
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=20:regular"
                                 foreground: a89984ff
                                 text: "󰕧 "
                                 right-margin: 2
               id == 8:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                                 right-margin: 7
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: ""
                                 right-margin: 7
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                                 right-margin: 7
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
                                 right-margin: 7
               id == 9:
                 map:
                   conditions:
                     focused:
                       map:
                         conditions:
                           occupied:
                             - string: {text: "["}
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: ""
                                 right-margin: 7
                             - string: {text: "] "}
                           ~occupied:
                             - string: {text: "["}
                             - string:
                                 foreground: a89984ff
                                 text: ""
                                 right-margin: 7
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                             - string: {text: "] "}
                     ~focused:
                       map:
                         conditions:
                           occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 text: " "
                                 right-margin: 7
                           ~occupied:
                             - string:
                                 font: "SauceCodePro Nerd Font:size=18:regular"
                                 foreground: a89984ff
                                 text: " "
                                 right-margin: 7
   right:
     - mem:
         content:
           - string: 
               text: ""
               font: Font Awesome 6 Free:style=solid:size=15
               foreground: b16286ff
               right-margin: 6
           - string:
               text: "{percent_used}% ({used:mb}MB)"
               foreground: b16286ff
           - string: { text: " | " }
     - cpu:
         content:
           map:
             conditions:
               id < 0:
                 - string: 
                     text: ""
                     font: Font Awesome 6 Free:style=solid:size=15
                     foreground: 83a598ff
                     right-margin: 6
                 - string:
                     foreground: 83a598ff
                     text: "{cpu}%"
                 - string: { text: " | " }
     - network:
         name: enp8s0
         poll-interval: 1
         content:
           map:
             conditions:
               state == up:
                 - string:
                     text: "󰖩 "
                     font: "SauceCodePro Nerd Font:size=18:regular"
                     foreground: b8bb26ff
                 - string:
                     text: "{dl-speed:mb:.1}d/{ul-speed:mb:.1}u"
                     foreground: b8bb26ff
                 - string:
                     text: " | "
                     foreground: b8bb26ff
               state != up:
                 - string:
                     text: "󰖪 "
                     font: "SauceCodePro Nerd Font:size=18:regular"
                 - string:
                     text: "{dl-speed}/{ul-speed:2}"
                 - string:
                     text: " | "
     - clock:
         date-format: "%b %d, %a (%Y)"
         time-format: "%I:%M %p :%S"
         content:
           - string: 
               text: ""
               font: "Font Awesome 6 Free:style=solid:size=15"
               foreground: fe8019ff
               right-margin: 6
           - string: 
               text: "{date}"
               foreground: fe8019ff
           - string: { text: " | " }
           - string: 
               text: ""
               font: "Font Awesome 6 Free:style=solid:size=15"
               foreground: fe8019ff
               right-margin: 6
           - string: 
               text: "{time}"
               foreground: fe8019ff


         # anchors:
         #   - base: &river_base
         #       margin: 6
         #       conditions:
         #         id == 1: {string: {text: 󰀚 }}  
         #         id == 2: {string: {text: 󰎧 }}  
         #         id == 3: {string: {text: 󰎪 }}  
         #         id == 4: {string: {text: 󰎭 }}  
         #         id == 5: {string: {text: 󰎱 }}  
         #         id == 6: {string: {text: 󰎳 }}  
         #         id == 7: {string: {text: 󰎶 }}  
         #         id == 8: {string: {text: 󰎹 }}  
         #         id == 9: {string: {text: 󰎼 }}  
         #         id == 10: {string: {text: 󰽽}}  
         #   content:
         #     # map:
         #     #   on-click:
         #     #     left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
         #     #     right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
         #     #     middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
         #     conditions:
         #       state == urgent:
         #         map:
         #           <<: *river_base
         #           deco: {background: {color: D08770ff}}
         #      state == focused:
         #        map:
         #          <<: *river_base
         #          foreground: ffffffff
         #      state == visible:
         #        map:
         #          conditions:
         #            ~occupied: {map: {<<: *river_base}}
         #            occupied: {map: {<<: *river_base}}
         #      state == unfocused:
         #        map:
         #          <<: *river_base
         #      state == invisible:
         #        map:
         #          conditions:
         #            ~occupied: {empty: {}}
         #            occupied: {map: {<<: *river_base}}
